<a href="https://colab.research.google.com/github/fersoria001/ColabNotebooks/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dfnew = pd.read_csv('week_one.csv')
dfnew = df.fillna(' ')
dfnew.columns.tolist()

['name',
 'sets',
 'reps',
 'rm',
 'category',
 'subcategory',
 'percentage',
 'weight']

In [ ]:
dfnew

,name,sets,reps,rm,category,subcategory,percentage,weight
0,Squats,5,5,120,main,legs,70%,84.0 kg
1,Leg Press,4,8,120,-,legs,50%,60.0 kg
2,Romanian Deadlifts,4,6,120,-,legs,50%,60.0 kg
3,Femoral Biceps Curl,3,12,120,-,legs,30%,36.0 kg
4,Bench Press,5,5,140,main,push,70%,98.0 kg
5,Incline Bench,4,8,140,-,push,50%,70.0 kg
6,Dumbell Flyes,4,6,140,-,push,50%,70.0 kg
7,Tricep Dips,3,12,140,-,push,30%,42.0 kg
8,Deadlifts,5,5,90,main,pull,70%,63.0 kg
9,Pull-ups,4,8,90,-,pull,50%,45.0 kg
10,Barbell Rows,4,6,90,-,pull,50%,45.0 kg
11,Bicep Curls,3,12,90,-,pull,30%,27.0 kg

In [ ]:
pd.set_option('display.max_colwidth', None)

tables = []
for i in range(0, len(dfnew), 4):
    table = dfnew.iloc[i:i+4]
    tables.append(table)

for i, table in enumerate(tables):
    print(f'Table {i+1}:')
    print(table.to_string(index=False))

Table 1:
               name  sets  reps  rm category subcategory percentage  weight
             Squats     5     5 120     main        legs        70% 84.0 kg
          Leg Press     4     8 120        -        legs        50% 60.0 kg
 Romanian Deadlifts     4     6 120        -        legs        50% 60.0 kg
Femoral Biceps Curl     3    12 120        -        legs        30% 36.0 kg
Table 2:
         name  sets  reps  rm category subcategory percentage  weight
  Bench Press     5     5 140     main        push        70% 98.0 kg
Incline Bench     4     8 140        -        push        50% 70.0 kg
Dumbell Flyes     4     6 140        -        push        50% 70.0 kg
  Tricep Dips     3    12 140        -        push        30% 42.0 kg
Table 3:
        name  sets  reps  rm category subcategory percentage  weight
   Deadlifts     5     5  90     main        pull        70% 63.0 kg
    Pull-ups     4     8  90        -        pull        50% 45.0 kg
Barbell Rows     4     6  90        -        pull        50% 45.0 kg
 Bicep Curls     3    12  90        -        pull        30% 27.0 kg

In [ ]:
import json
# Convert DataFrame to JSON format
json_data = dfnew.to_json(indent=4)

# Save JSON data to a file
with open("table_view.json", "w") as file:
    file.write(json_data)

NameError: ignored

In [ ]:

class Exercise:
    def __init__(self, name, sets, reps, rm, category, subcategory, percentage):
        self.name = name
        self.sets = sets
        self.reps = reps
        self.rm = rm
        self.category = category
        self.subcategory = subcategory
        self.percentage = percentage
        self.weight = None

    def calculate_weight(self):
      self.weight = self.rm * (self.percentage / 100)
      return self.weight

    def calculate_tonnage(self):
      self.tonnage = self.sets * self.reps * self.weight * (self.percentage / 100)

    def calculate_volume(self):
      self.volume = self.sets * self.reps

    # Define __str__ method to specify the string representation of the object
    def __str__(self):
        return (f"Exercise(name={self.name}, reps_min={self.sets}, "
                f"reps_max={self.reps}, rm={self.rm}, "
                f"subcategory={self.subcategory}, percentage={self.percentage})")

In [ ]:

class WeekRoutine:
    def __init__(self,rm, subcategory_list, reps, names_list, percentages, main_lifts) -> None:
        self.rm = rm
        self.main = 'main'
        self.subcategory_list = subcategory_list
        self.reps = reps
        self.names_list = names_list
        self.percentages = percentages
        self.main_lifts = main_lifts

    def getExercises(self):
        exercise_objects = []
        for j in range(len(self.names_list)):
            for i in range(len(self.names_list[j])):
                category = self.main if self.names_list[j][i] in self.main_lifts else None
                exercise = Exercise(
                    self.names_list[j][i],
                    self.reps[i][0],
                    self.reps[i][1],
                    self.rm[j],
                    category,
                    self.subcategory_list[j],
                    self.percentages[i]
                    )
                exercise_objects.append(exercise)
                return exercise_objects

In [ ]:

class DataFrame:
    def __init__(self, exercise_array, day_names) -> None:
        self.exercise_array = exercise_array
        self.df = pd.DataFrame([vars(e) for e in self.exercise_array])
        self.day_names = day_names
        self.styleFormat()
    def styleFormat(self):
        self.df = self.df.fillna('-')
        self.df['weight'] = [f"{round(ex.calculate_weight(), 1)} kg" for ex in self.exercise_array]
        self.df['percentage'] = self.df['percentage'].astype(str) + '%'
        pd.set_option('display.max_colwidth', 200)




    def defineChunks(self):
        chunk_array = []
        for i in range(0, len(self.df), 4):
            chunk = self.df.iloc[i:i+4]
            chunk = chunk.style.set_caption(f'{self.day_names[i//4]}')
            chunk_array.append(chunk)
            return chunk_array

In [ ]:
rm = [120, 140, 90]
main = 'main'
subcategory_list = ['legs','push', 'pull']
reps = [[5,5],[4,8],[4,6],[3, 12]]
names_list = [['Squats', 'Leg Press', 'Romanian Deadlifts', 'Femoral Biceps Curl']
          ,['Bench Press', 'Incline Bench', 'Dumbell Flyes', 'Tricep Dips'],
          ['Deadlifts', 'Pull-ups', 'Barbell Rows', 'Bicep Curls']]
percentages = [70,50,50,30]
main_lifts = ['Squats', 'Bench Press', 'Deadlifts']
day_names = ['Day 1 (pull, deadlift focused)', 'Day 2 (push, bench press focused)', 'Day 3 (push, legs focused)']
week_one = WeekRoutine(rm,subcategory_list,reps,names_list,percentages,main_lifts)
exercises_week_one = week_one.getExercises()
week_one_df = DataFrame(exercises_week_one, day_names)
week_one_views = week_one_df.defineChunks()
#for view in week_one_views:
 # display(view)